# -*- coding: utf-8 -*-
"""Project_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8XNTgdU6hjC20frpK5XyNC8wig8nhSL

# **NOTE:** Use File > Save a copy in Drive to make a copy before doing anything else

# Project 6: Data Exploration and Visualization

### Overview

In this project, you will apply data exploration and visualization techniques to a real-world dataset of your choice. You'll practice using pandas for data analysis and create meaningful visualizations to gain insights from your data. This project builds on your Python programming skills while introducing you to the exciting world of data science.

In [Lab6](https://colab.research.google.com/drive/1WxHaCZlN8d0kVgTCBmbMWmF29TM4pDJs?usp=sharing), you explore the titanic dataset and you should use it as a sample and pick a dataset of your interest to do a similar data exploration and visualization.

# New Section

### Project Objectives

*   Find and select a dataset from a real-world data source
*   Formulate a clear inquiry question based on your chosen dataset


*   Perform exploratory data analysis using pandas functions
*   Create at least two meaningful data visualizations


*   Analyze your findings and answer your inquiry question
*   Reflect on the insights gained through data exploration

### Data Sources
You can choose from various online data sources such as:

* [Kaggle](https://www.kaggle.com/datasets) - Wide variety of datasets
* [data.gov](https://www.data.gov/) - U.S. government data
* [Our World in Data](https://ourworldindata.org/) - Global development data
* [GitHub](https://github.com/datasets) - Curated datasets
* [Google Dataset Search](https://datasetsearch.research.google.com/) - Search for datasets
* Or any other reliable data source you find interesting

## Part 1: Dataset Selection and Initial Exploration

#### TODO Tasks:

1. Select Your Dataset: Choose a dataset that interests you. Make sure it has at least 100 rows and multiple columns with different data types (e.g., numerical, categorical, dates).

Please create either text or code cells in between the TODO tasks to do the work.

2. Import Libraries: Import the necessary libraries (pandas, matplotlib, seaborn) at the beginning of your notebook by creating code cells below this text cell.

3. Load Your Data: Load your chosen dataset using pandas and save it to a pandas dataframe. Please create a code cell below this text cell to do it.

4. Data Summary: Use the following functions to do inital exploration your dataset:

* info() - Display information about the dataset structure
* describe() - Show statistical summary of numerical columns
* head() - Display the first 5 rows (df.head())
* shape - Show the dimensions of the dataset (e.g. df.shape)
* columns - Get the column names (e.g. df.columns)

You may use 5 code cells below this text cell to accomplish it.

5. Inquiry Question: Write a clear, specific question that you want to answer using your dataset by creating a text cell below and **write the question in bold please.**

For example:

* "How has the average temperature changed in major cities over the past decade?"

* "What factors are most strongly correlated with housing prices?"

* "Is there a relationship between education level and income?"

## Part 2: Data Visualization and Analysis

#### TODO Tasks:

1. Data Cleaning (if necessary): Check for and handle any missing values, duplicates, or data quality issues.

**NOTE: This could be a daunting task even for seasoned data scientists. My suggestion is to use a dataset that is already clean if you can for the purpose of completing this assignment in a week.**

Examples:

* Checking for missing values: df.isnull().sum()
* Dropping rows with any missing values: df.dropna(inplace=True)
* Dropping columns with all missing values: df.dropna(axis=1, how='all', inplace=True)
* Removing duplicate row: df.drop_duplicates(inplace=True)

2. Create Visualizations: Create at least 2 different types of visualizations that help answer your research question. Choose from:

* Bar charts
* Line plots
* Scatter plots
* Histograms
* Box plots
* Heatmaps
* Any other appropriate visualization

3. Customize Your Plots: Make sure your visualizations are clear and informative by:

* Adding appropriate titles
* Labeling axes
* Using colors effectively
* Adding legends when necessary

Please create code cells below this to create your visualizations.

4. Analysis: Write 1-2 paragraphs discussing:

* Whether your research question can be answered with the available data
* What insights you discovered through your visualizations
* Any unexpected or interesting findings
* Limitations of your analysis
* Suggestions for further investigation

Please create a text cell below this cell to write your analysis.

## Submission Requirements

## NOTE: If you use a local dataset, you MUST submit the dataset along with your notebook to get credit.

* Download your notebook as CS110_Project6.ipynb
* Ensure all TODO tasks are completed
* Make sure your code runs without errors
* Include clear comments explaining your work
* Submit the notebook file

## Grading Criteria (5 points)

* Dataset Selection: Appropriate choice of dataset with sufficient complexity (0.5 point)
* Inquiry Question: Clear, specific, and answerable with the chosen data (1 point)
* Data Exploration: Proper use of pandas functions for initial analysis (0.5 point)
* Visualizations: At least 2 clear, well-formatted, and relevant plots (1 point)
* Analysis: Thoughtful interpretation of findings and answer to research question (1 point)
* Code Quality: Clean, commented, and well-organized code (1 point)

Remember: The goal is not just to create visualizations, but to use them to gain meaningful insights about your data. Think like a data scientist and let your curiosity guide your exploration!
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#I asked gemini to give me a link for this since mine wasnt working, it uses the stuff from
# kraggle link "https://www.kaggle.com/datasets/padmapriyatr/netflix-titles"
URL = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv"

df = pd.read_csv(URL)

#filterdf_recent = df[(df['type'] == 'Movie') & (df['release_year'] >= 2000) & (df['release_year'] <= 2021)].copy()

#sorting
def assign_age(rating):
    if rating in ['G', 'TV-G', 'TV-Y', 'TV-Y7', 'PG', 'TV-PG']:
        return 'Kids'
    if rating in ['PG-13', 'TV-14']:
        return 'Teens'
    if rating in ['R', 'NC-17', 'TV-MA']:
        return 'Adults'
    return 'Other'

df_recent['age_group'] = df_recent['rating'].apply(assign_age)

#First Visualization
age_group_counts = df_recent['age_group'].value_counts(normalize=True).loc[['Kids', 'Teens', 'Adults']]

plt.figure(figsize=(8, 8))
plt.pie(age_group_counts, labels=age_group_counts.index, autopct='%1.1f%%', startangle=90, colors=['pink', 'mediumpurple', 'skyblue'])
plt.title('Proportion of Movies by Age Group (2000 and Newer)')
plt.axis('equal')

#Second Visualization
plt.figure(figsize=(10, 6))
my_colors = ['pink', 'mediumpurple', 'skyblue']
#gemini helped with this
sns.countplot(
    data=df_recent,
    x='age_group',
    order=['Kids', 'Teens', 'Adults'],
    palette=my_colors
)

#labels
plt.title('Distribution of Movie Ratings (2000-2021)')
plt.xlabel('Target Age Group')
plt.ylabel('Total Number of Movies')

plt.show()

"""My research question was to figure out which age group had the most movies released on Netflix from 2000 to 2021. Based on the data and graph I made, I came to a conclusion. The bar chart showed that most movies were made for adults, then teens, and finally kids. The Pie chart shows the percentages of movies released in each age group. This shows that Netflix focused on marketing towards an older audience, most likely since they are the ones who pay for it.

It shocked me because I feel like I see a new kids' movie released every week. The Teens and Kids categories seem pretty close, but the adults tower over them. One limitation of this project is that the data only shows which age group is targeted, not which age group actually watched it. If I continue this project, I would like to look into what genres were popular, which could explain why there is so much adult-rated content on Netflix.
"""